Importing zdbc into ziti-jdbc
openziti/ziti-sdk-jvm pull request #329
Opened 2022-07-06 20:18 UTC by tburtchell

Importing the ZDBC wrapper from test kitchen into the java sdk proper

2022-07-07 13:44 UTC, ekoby requested changes
drop all .idea/ and .mvn stuff
there is a `target` folder as well

2022-07-07 20:39 UTC, tburtchell commented
intellij files, targets, and such have been removed.

The jpa sample is standalone, and has the ability to be built with either maven or gradle.  I'd like to leave the .mvn files in there.  Super hate,  or just regular hate for that idea?

2022-07-08 14:05 UTC, ekoby commented
> intellij files, targets, and such have been removed.
> 
> The jpa sample is standalone, and has the ability to be built with either maven or gradle. I'd like to leave the .mvn files in there. Super hate, or just regular hate for that idea?

I'd remove all wrappers from the submodules -- it just creates a lot of duplicated files. 
Also all samples along with `network/` should be moved to top samples umbrella

2022-07-13 13:48 UTC, ekoby approved these changes

2022-07-13 14:23 UTC, merged